title_format: §0■§e■§0■
Player_name:
  syakaijin_4869:
    sound: BLOCK_BELL_RESONATE
    title: フェミ警告
    words:
    - 性的同意
    - 性的搾取
    - ゾーニング
    - 性的モノ化
    - ジェンダー
    - 家父長制
    - ガラスの天井
    - セクシズム
    - マンスプレイニング
    - ミソジニー
    - セックス(身体的性別)
  MaiZe2505:
    sound: BLOCK_BELL_RESONATE
    title: 警告
    words:
    - 性的同意
    - 性的搾取
    - ゾーニング
    - 性的モノ化
    - ジェンダー
    - 家父長制
    - ガラスの天井
    - セクシズム
    - マンスプレイニング
    - ミソジニー
    - セックス(身体的性別)
